// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn4icez2cBW2qhozzq5f91VnXGmkFMWtY',
    appId: '1:704416646683:web:55a4b3d36a422f606e9abe',
    messagingSenderId: '704416646683',
    projectId: 'tara-travel-30b8e',
    authDomain: 'tara-travel-30b8e.firebaseapp.com',
    storageBucket: 'tara-travel-30b8e.firebasestorage.app',
    measurementId: 'G-NZP0KG05M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ArRe2MzBRFmsvnvN9wWRrk6MZuhYxSE',
    appId: '1:704416646683:android:a1d190172d5c7c676e9abe',
    messagingSenderId: '704416646683',
    projectId: 'tara-travel-30b8e',
    storageBucket: 'tara-travel-30b8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLsn4FUMFjI8kLdMthD-4RWIQXuP_icCo',
    appId: '1:704416646683:ios:931a05ab6b80598c6e9abe',
    messagingSenderId: '704416646683',
    projectId: 'tara-travel-30b8e',
    storageBucket: 'tara-travel-30b8e.firebasestorage.app',
    iosBundleId: 'com.example.taraTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLsn4FUMFjI8kLdMthD-4RWIQXuP_icCo',
    appId: '1:704416646683:ios:931a05ab6b80598c6e9abe',
    messagingSenderId: '704416646683',
    projectId: 'tara-travel-30b8e',
    storageBucket: 'tara-travel-30b8e.firebasestorage.app',
    iosBundleId: 'com.example.taraTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn4icez2cBW2qhozzq5f91VnXGmkFMWtY',
    appId: '1:704416646683:web:e285097c8c6000126e9abe',
    messagingSenderId: '704416646683',
    projectId: 'tara-travel-30b8e',
    authDomain: 'tara-travel-30b8e.firebaseapp.com',
    storageBucket: 'tara-travel-30b8e.firebasestorage.app',
    measurementId: 'G-RLJ5EQ2C5H',
  );
}
