# generate_changelog.ps1
# Usage: pwsh tools/generate_changelog.ps1
# Auto-invoked by .git/hooks/post-commit after every commit.

param([string]$RepoRoot = (Split-Path -Parent $PSScriptRoot))

$MemFile = if (Test-Path (Join-Path $RepoRoot "docs/IMPLEMENTATION_MEMORY.md")) { Join-Path $RepoRoot "docs/IMPLEMENTATION_MEMORY.md" } else { Join-Path $RepoRoot "IMPLEMENTATION_MEMORY.md" }
$OutFile = if (Test-Path (Join-Path $RepoRoot "docs/CHANGELOG.md")) { Join-Path $RepoRoot "docs/CHANGELOG.md" } else { Join-Path $RepoRoot "CHANGELOG.md" }

# 1. Parse the index table
$indexEntries = [System.Collections.Generic.List[hashtable]]::new()
$inTable      = $false
$content      = Get-Content $MemFile -Encoding UTF8

foreach ($line in $content) {
    if ($line -match "^\|\s*\*\*``IMP-") { $inTable = $true }
    if (-not $inTable) { continue }
    if ($line -match "^\|\s*\*\*``(IMP-\d+)``\*\*\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*(.+?)\s*\|") {
        $indexEntries.Add(@{ Id = $Matches[1].Trim(); Date = $Matches[2].Trim(); Component = $Matches[3].Trim(); Summary = $Matches[4].Trim() })
    }
}

# 2. Parse detailed sections (### `IMP-XXX` · Title)
$detailMap  = [System.Collections.Generic.Dictionary[string,hashtable]]::new()
$currentImp = $null
$bodyLines  = [System.Collections.Generic.List[string]]::new()

foreach ($line in $content) {
    if ($line -match "^###\s+``(IMP-\d+)``\s*[·.]\s*(.+)$") {
        # Capture before any other -match/-notmatch clobbers $Matches
        $capturedId    = $Matches[1]
        $capturedTitle = $Matches[2].Trim()
        if ($null -ne $currentImp) {
            $detailMap[$currentImp.Id] = @{ Title = $currentImp.Title; Body = ($bodyLines | Where-Object { $_ -notmatch "^---$" }) -join [System.Environment]::NewLine }
        }
        $currentImp = @{ Id = $capturedId; Title = $capturedTitle }
        $bodyLines  = [System.Collections.Generic.List[string]]::new()
    } elseif ($null -ne $currentImp) {
        $bodyLines.Add($line)
    }
}
if ($null -ne $currentImp) {
    $detailMap[$currentImp.Id] = @{ Title = $currentImp.Title; Body = ($bodyLines | Where-Object { $_ -notmatch "^---$" }) -join [System.Environment]::NewLine }
}

# 3. Build git commit map
$gitLog    = & git -C $RepoRoot log --pretty=format:"%h|%s|%as" 2>$null
$commitMap = @{}
foreach ($entry in $gitLog) {
    $parts = $entry -split "\|", 3
    if ($parts.Count -lt 3) { continue }
    if ($parts[1] -match "(IMP-\d+)") {
        $id = $Matches[1]
        if (-not $commitMap.ContainsKey($id)) { $commitMap[$id] = @{ Hash = $parts[0].Trim(); Subject = $parts[1].Trim() } }
    }
}

# 4. GitHub base URL
$origin = & git -C $RepoRoot remote get-url origin 2>$null
$ghBase = $null
if ($origin -match "github\.com[:/](.+?)(?:\.git)?$") { $ghBase = "https://github.com/$($Matches[1])/commit" }

# 5. Generate CHANGELOG.md
$now = Get-Date -Format "yyyy-MM-dd HH:mm"
$sb  = [System.Text.StringBuilder]::new()
$sb.AppendLine("# Tara Travel - Version Changelog") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("> Auto-generated from IMPLEMENTATION_MEMORY.md + git log") | Out-Null
$sb.AppendLine("> Last updated: **$now PHT**") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("---") | Out-Null
$sb.AppendLine("") | Out-Null

$grouped = $indexEntries | Sort-Object { [datetime]$_.Date } -Descending | Group-Object { $_.Date }

foreach ($group in $grouped) {
    $sb.AppendLine("## $($group.Name)") | Out-Null
    $sb.AppendLine("") | Out-Null
    foreach ($entry in ($group.Group | Sort-Object { [int]($_.Id -replace "IMP-","") } -Descending)) {
        $id = $entry.Id; $comp = $entry.Component; $sum = $entry.Summary
        $commit = $commitMap[$id]; $badge = ""
        if ($null -ne $commit) {
            $h = $commit.Hash
            $badge = if ($null -ne $ghBase) { " [commit:$h]($ghBase/$h)" } else { " commit:$h" }
        }
        $detail = $detailMap[$id]
        $title  = if ($null -ne $detail) { $detail.Title } else { $comp }
        $sb.AppendLine("### $id - $title$badge") | Out-Null
        $sb.AppendLine("") | Out-Null
        $sb.AppendLine("**Component**: $comp") | Out-Null
        $sb.AppendLine("") | Out-Null
        $sb.AppendLine("**Summary**: $sum") | Out-Null
        $sb.AppendLine("") | Out-Null
        if ($null -ne $detail -and $detail.Body.Trim().Length -gt 0) {
            $sb.AppendLine("<details>") | Out-Null
            $sb.AppendLine("<summary>Full implementation detail</summary>") | Out-Null
            $sb.AppendLine("") | Out-Null
            $sb.AppendLine($detail.Body.TrimEnd()) | Out-Null
            $sb.AppendLine("") | Out-Null
            $sb.AppendLine("</details>") | Out-Null
            $sb.AppendLine("") | Out-Null
        }
        $sb.AppendLine("---") | Out-Null
        $sb.AppendLine("") | Out-Null
    }
}
$sb.AppendLine("*Generated by tools/generate_changelog.ps1*") | Out-Null
$sb.ToString() | Set-Content -Path $OutFile -Encoding UTF8
Write-Host "CHANGELOG.md written ($($indexEntries.Count) milestones)"
