-- Create stop_votes table for collaborative voting
CREATE TABLE stop_votes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    stop_id UUID NOT NULL, -- Logical ID generated by client
    member_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    upvote BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- A member can only vote once per stop
    UNIQUE(stop_id, member_id)
);

-- RLS Policies
ALTER TABLE stop_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Trip members can view votes"
    ON stop_votes FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM trip_members
            WHERE trip_members.trip_id = stop_votes.trip_id
            AND trip_members.user_id = auth.uid()
        )
    );

CREATE POLICY "Trip members can insert votes"
    ON stop_votes FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM trip_members
            WHERE trip_members.trip_id = stop_votes.trip_id
            AND trip_members.user_id = auth.uid()
        )
        AND member_id = auth.uid()
    );

CREATE POLICY "Trip members can update their own votes"
    ON stop_votes FOR UPDATE
    USING (
        member_id = auth.uid()
    );

CREATE POLICY "Trip members can delete their own votes"
    ON stop_votes FOR DELETE
    USING (
        member_id = auth.uid()
    );

-- Add realtime to stop_votes
ALTER PUBLICATION supabase_realtime ADD TABLE stop_votes;
