-- ═══════════════════════════════════════════════════════════════════════════
-- TARA TRAVEL · MIGRATION 027: DESTINATIONS SEED & ENHANCEMENTS
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Ensures image_url and coordinate columns exist on public.destinations and
-- populates real, curated Philippine travel hubs with high-resolution imagery.
-- ═══════════════════════════════════════════════════════════════════════════

-- Ensure columns exist
alter table public.destinations
  add column if not exists image_url text,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists trip_type text default 'sightseeing_tours';

-- Ensure RLS is active and public read policy is present
alter table public.destinations enable row level security;

drop policy if exists "Anyone can read destinations" on public.destinations;
create policy "Anyone can read destinations" on public.destinations for select using (true);

-- Upsert destinations
insert into public.destinations (
  name, country, distance_from_metro, best_mode, avg_cost_range, photo_emoji, tag, description,
  is_trending, is_weekend_getaway, is_recommended, recommended_reason, best_time_to_visit,
  image_url, latitude, longitude, trip_type
)
values
(
  'Boracay',
  'Philippines',
  '~315 km (1h flight from Manila)',
  '✈️ Flight + Boat',
  '₱8,000–₱16,000',
  '🏖️',
  'Beach',
  'World-famous powdery white sand, breathtaking tropical sunsets, and vibrant watersport adventures along Station 1 to 3.',
  true,
  false,
  true,
  'Top-rated beach in Southeast Asia with pristine shores and nightlife.',
  'Nov–May',
  'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
  11.9674,
  121.9248,
  'beach_coastal'
),
(
  'El Nido',
  'Philippines',
  '~420 km (1.2h flight from Manila)',
  '✈️ Flight + Van',
  '₱12,000–₱24,000',
  '🌴',
  'Nature',
  'Towering limestone karst cliffs, hidden lagoons, secret beaches, and crystalline turquoise snorkeling waters.',
  true,
  false,
  true,
  'Must-visit UNESCO biosphere with breathtaking lagoons and island hopping.',
  'Dec–May',
  'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80',
  11.1956,
  119.4075,
  'nature_outdoors'
),
(
  'Coron',
  'Philippines',
  '~300 km (1h flight from Manila)',
  '✈️ Flight + Boat',
  '₱10,000–₱20,000',
  '🤿',
  'Adventure',
  'World-class WWII Japanese shipwrecks, Kayangan Lake cleanest inland water, and Twin Lagoon thermocline swims.',
  true,
  false,
  true,
  'Renowned for crystal clear lakes and unforgettable wreck diving.',
  'Dec–May',
  'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
  11.9986,
  120.2043,
  'nature_outdoors'
),
(
  'Siargao',
  'Philippines',
  '~780 km (2h flight from Manila)',
  '✈️ Flight + Motorbike',
  '₱9,000–₱18,000',
  '🏄',
  'Adventure',
  'The surfing capital of the Philippines. Legendary Cloud 9 breaks, endless coconut palm roads, and serene Sugba Lagoon.',
  true,
  false,
  true,
  'Vibrant surf culture, cafes, and laid-back island vibes.',
  'Jul–Nov (Surf) / Mar–Oct (Sun)',
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  9.8580,
  126.0460,
  'sports_active'
),
(
  'Baguio City',
  'Philippines',
  '~245 km (~4-5h drive via TPLEX)',
  '🚗 Car / Bus',
  '₱3,500–₱8,000',
  '🌲',
  'City',
  'The Summer Capital of the Philippines. Crisp pine air, strawberry farms, Burnham Park, and artistic heritage at Camp John Hay.',
  false,
  true,
  true,
  'Refreshing cool weather escape just a scenic expressway drive away.',
  'Nov–Feb',
  'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
  16.4023,
  120.5960,
  'staycation'
),
(
  'Tagaytay',
  'Philippines',
  '~60 km (~1.5h drive via SLEX/CALAX)',
  '🚗 Car',
  '₱2,000–₱5,500',
  '🌋',
  'Nature',
  'Cool highland breezes, panoramic views of Taal Volcano and Lake, roadside bulalo, and charming farm-to-table ridge bistros.',
  false,
  true,
  true,
  'Quick and cozy road trip escape with magnificent lake ridge dining.',
  'Year-round',
  'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80',
  14.1153,
  120.9621,
  'food_crawl'
),
(
  'Batanes',
  'Philippines',
  '~680 km (1.5h flight from Manila)',
  '✈️ Flight + Tricycle',
  '₱18,000–₱35,000',
  '⛰️',
  'Cultural',
  'Sweeping emerald rolling hills, Marlboro Hills sea vistas, historic Ivatan stone houses, and tranquil Pacific cliffs.',
  true,
  false,
  true,
  'Unmatched dramatic cliffs, peaceful heritage, and pristine landscapes.',
  'Dec–May',
  'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
  20.4485,
  121.9708,
  'sightseeing_tours'
),
(
  'Cebu & Moalboal',
  'Philippines',
  '~570 km (1.2h flight from Manila)',
  '✈️ Flight + Bus',
  '₱7,500–₱15,000',
  '🐟',
  'Adventure',
  'World-famous sardine run just meters off the beach, sea turtles, Kawasan Falls canyoneering, and Magellan’s Cross history.',
  true,
  false,
  true,
  'Epic canyoneering waterfalls and rich colonial landmarks.',
  'Dec–May',
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
  10.3157,
  123.8854,
  'adventure_trekking'
),
(
  'Sagada',
  'Philippines',
  '~390 km (~10-12h scenic drive/bus)',
  '🚌 Bus / Van',
  '₱4,500–₱9,000',
  '☕',
  'Cultural',
  'Misty Kiltepan sunrise sea of clouds, mystical Sumaguing Cave spelunking, hanging coffins, and fresh mountain Arabica coffee.',
  false,
  false,
  true,
  'Peaceful mountain sanctuary with rich Igorot culture and spelunking.',
  'Nov–Feb',
  'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1200&q=80',
  17.0833,
  120.9000,
  'backpacking'
),
(
  'La Union (San Juan)',
  'Philippines',
  '~270 km (~4h drive via TPLEX)',
  '🚗 Car / Bus',
  '₱3,500–₱7,500',
  '🌊',
  'Beach',
  'Accessible surf destination on the Luzon west coast, bustling food park community, beach bars, and vibrant sunset nightlife.',
  true,
  true,
  true,
  'Favorite weekend surf spot with creative food concepts and chill music.',
  'Oct–Mar (Surf) / Apr–Jun (Calm)',
  'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80',
  16.6750,
  120.3394,
  'beach_coastal'
),
(
  'Bohol & Panglao',
  'Philippines',
  '~630 km (1.3h flight from Manila)',
  '✈️ Flight + Van',
  '₱8,000–₱16,000',
  '🐒',
  'Nature',
  'Iconic cone-shaped Chocolate Hills, tiny Philippine tarsiers, Loboc river cruise lunch, and Alona Beach dive trips.',
  true,
  false,
  true,
  'Eclectic wonders from world-famous geodiversity hills to lively beach strips.',
  'Dec–May',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
  9.8500,
  124.1435,
  'sightseeing_tours'
),
(
  'Camiguin Island',
  'Philippines',
  '~780 km (Flight / Ferry from Bohol/CDO)',
  '✈️ Flight + Ferry',
  '₱7,000–₱14,000',
  '🌋',
  'Nature',
  'The "Island Born of Fire". White Island horseshoe sandbar, Katibawasan Falls, sunken cemetery cross, and sweet lanzones.',
  false,
  false,
  true,
  'Untouched volcanic paradise with crystal springs and lush rainforests.',
  'Mar–Oct',
  'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=80',
  9.1732,
  124.7299,
  'nature_outdoors'
),
(
  'Intramuros, Manila',
  'Philippines',
  'Metro Manila',
  '🚗 Car / LRT',
  '₱800–₱2,500',
  '🏛️',
  'Cultural',
  'The historic 16th-century Spanish walled enclave. Fort Santiago, San Agustin Church (UNESCO), cobblestone streets, and bamboo bike tours.',
  false,
  true,
  false,
  'Rich colonial history, museums, and romantic rooftop dinners right in the city.',
  'Year-round',
  'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
  14.5896,
  120.9747,
  'sightseeing_tours'
),
(
  'Iloilo & Guimaras',
  'Philippines',
  '~470 km (1h flight from Manila)',
  '✈️ Flight + Ferry',
  '₱6,000–₱12,000',
  '🥣',
  'Cultural',
  'City of Love known for heritage churches, authentic La Paz Batchoy, Molo Mansion, and a 15-minute boat ride to world-famous sweet mangoes.',
  false,
  false,
  true,
  'Culinary capital UNESCO Creative City of Gastronomy with gentle charm.',
  'Nov–May',
  'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
  10.7202,
  122.5621,
  'food_crawl'
)
on conflict do nothing;
